name: flavor_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_flavorizr: ^2.1.3
  package_info_plus: ^1.4.2

dev_dependencies: 
  change_app_package_name: ^1.1.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  ide: "vscode"

  flavors:
    development:
      app:
        name: "Development Flavor"

      android:
        applicationId: "com.dev.flavorsdemo"

      ios:
        bundleId: "com.dev.flavorsdemo"
        # buildSettings:
        #   # Development Team is visible in the apple developer portal 
        #   DEVELOPMENT_TEAM: YOURDEVTEAMID 
        #   PROVISIONING_PROFILE_SPECIFIER: "Dev-ProvisioningProfile"

    staging:
      app:
        name: "Staging App"

      android:
        applicationId: "com.staging.flavorsdemo"
      ios:
        bundleId: "com.staging.flavorsdemo"
        # buildSettings:
        #   DEVELOPMENT_TEAM: YOURSTAGINGTEAMID
        #   PROVISIONING_PROFILE_SPECIFIER: "Staging-ProvisioningProfile"

    production:
      app:
        name: "Production App"

      android:
        applicationId: "com.production.flavorsdemo"
      ios:
        bundleId: "com.production.flavorsdemo"
        # buildSettings:
        #   DEVELOPMENT_TEAM: YOURPRODUCTIONTEAMID
        #   PROVISIONING_PROFILE_SPECIFIER: "Production-ProvisioningProfile"